#!/usr/bin/env python3
import socket
import time
import os
from easygui import *

host = "192.168.0.4"
port = 4200

class Main:
    def __init__(self):
        self.s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.address = (host, port)

    def send_order(self, order):
        self.s.connect(self.address)
        self.msg = order
        self.s.send(bytes(self.msg, "utf8"))
        self.confrimation = msgbox('Your order went through', 'Confrimation')
try:
    m = Main()
    msg1 = "What do you want to order"
    title = "Order"
    choices = ["music", "movies"]
    choice = choicebox(msg1, title, choices)
    if choice == "music":
        finalorder = enterbox(title="Order", msg="what is the name of the movie song you would like?")
        name = enterbox(title="Order", msg="whats is your name(format as such:<first name> <last initial>)?")
        finala = ', "song=' + finalorder + '" : "' + name + '"}'
        m.send_order(finala)
    elif choice == "movies":
        finalorder = enterbox(title="Order", msg="what is the name of the movie you would like?")
        name = enterbox(title="Order", msg="whats is your name(format as such:<first name> <last initial>)?")
        finala = ', "movie=' + finalorder + '" : "' + name + '"}'
        m.send_order(finalorder)
except ConnectionRefusedError:
    errorrr = msgbox('ConnectionRefusedError                                                        Black Market servers are either down or undergoing maintenance, making it unable to send order[0]', 'Connection Refused')